org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

java_version=21
minecraft_version=1.21.4
fabric_loader_version=0.16.9
mod_compatibility_version=21

# For snapshots, append -SNAPSHOT
mcef_version=2.1.6-1.21.4

mod_id=mcef
mod_name=MCEF (Minecraft Chromium Embedded Framework)

mod_vendor=CinemaMod Group

fabric_loom_version=1.7-SNAPSHOT
cursegradle_version=1.4.0
shadow_version=8.1.1
