plugins {
    id 'fabric-loom'
    id 'maven-publish'
}

sourceCompatibility = JavaLanguageVersion.of(java_version as int)
targetCompatibility = JavaLanguageVersion.of(java_version as int)

repositories {
    mavenCentral()
    maven { url = 'https://maven.fabricmc.net/' }
    mavenLocal()
    maven {
        name = 'ParchmentMC'
        url = 'https://maven.parchmentmc.org'
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings "net.fabricmc:yarn:1.21.4+build.7:v2"
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
}

sourceSets {
    jcef {
        java {
            srcDir "java-cef/java"
            exclude "**/tests/**"
        }
    }

    main {
        compileClasspath += jcef.output
        runtimeClasspath += jcef.output
    }
}

processResources.dependsOn(processJcefResources)

jar {
    from sourceSets.jcef.output.classesDirs
    from sourceSets.jcef.output.resourcesDir
}

idea {
    module {
        excludeDirs += file("java-cef/java/tests")
        inheritOutputDirs true
    }
}


task sourceJar(type: Jar) {
    from sourceSets.main.allSource
    archiveClassifier.set('sources')
}

jar {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    from('src/main/resources/META-INF/services') {
        into('META-INF/services')
    }
}

afterEvaluate {
    publishing {
        repositories {
            maven {
                name = "mirageRepository"
                url = "https://repo.mirage-play.com/releases"
                credentials {
                    username = System.getenv("USERNAME")
                    password = System.getenv("TOKEN")
                }
                authentication {
                    basic(BasicAuthentication)
                }
            }
        }
        publications {
            maven(MavenPublication) {
                groupId = 'com.cinemamod'
                artifactId = 'mcef'
                version = mcef_version
                from(components.java)
                artifact(sourceJar) {
                    classifier "sources"
                }
            }
        }
    }
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

tasks.withType(Javadoc) {
    options.encoding = 'UTF-8'
}